### ISSUE TITLE
CREATE logo in header + site colour

### ISSUE THREAD

**Issue by Anthony-1811** [CreateUNSW/createunsw.github.io#8]
Are we able to get the create logo in the header and change the header colour and potentially the whole site in CREATE blue?

**Comment by Gnahz3640** [comment]
https://drive.google.com/drive/folders/0BzPz9Imh10VITEY1U1k0T2picTg

For reference, you can find club colours here (along with high-res images)

**Comment by cjoy** [comment]
@Anthony-1811 
Yeah I did manage to get the create logo in the header, but even with a compressed and resized version, Github's CDN is pretty slow (especially when serving assets). I decided to remove it and stick with good old text 

As for changing the colour scheme for the whole site to blue... I reckon it won't be as aesthetically pleasing as our current design (white, red and grey). 

http://www.websitebuilderexpert.com/how-to-choose-color-for-your-website/
https://blog.crazyegg.com/2011/12/30/pick-website-color-combination/

@Gnahz3640 
As for high-res images, I am currently using the ones that are hosted on Facebook as their CDN is pretty fast. Otherwise we would have to pay for our own CDN (or setup our own via paid servers), to serve those "high-res" images pretty quickly.

Btw. The sales section is ready!

Thanks for the suggestion.
